CREATE DATABASE KRISHNA ;
USE KRISHNA ;
CREATE TABLE STUDENT1
(
 ROLLNO INT,
 FNAME VARCHAR(35),
 LNAME VARCHAR(35),
 CITY VARCHAR(35)
) ;
SELECT *  FROM STUDENT1 ;
INSERT INTO STUDENT1 (ROLLNO, FNAME, LNAME, CITY) VALUES ( 1 ,"RAKESH","ROSHAN","AHMEDABAD");
INSERT INTO STUDENT1 (ROLLNO, FNAME, LNAME, CITY) VALUES ( 2 ,"RAM","RAJ","GANDHINAGAR");
INSERT INTO STUDENT1 (ROLLNO, FNAME, LNAME, CITY) VALUES ( 3 ,"ROCKEY","PATHAK","MUBAI");
INSERT INTO STUDENT1 (ROLLNO, FNAME, LNAME, CITY) VALUES ( 4 ,"RAJ","SINGH","BARODA");
INSERT INTO STUDENT1 (ROLLNO, FNAME, LNAME, CITY) VALUES ( 5 ,"HIMESH","MADAN","BENG");
INSERT INTO STUDENT1 (ROLLNO, FNAME, LNAME, CITY) VALUES ( 6 ,"RAJESH","MADAN","MUMBAI");
INSERT INTO STUDENT1 (FNAME,LNAME) VALUES ("MISH","MITAL");

SELECT FNAME , LNAME from STUDENT1 ;

SELECT ROLLNO FROM STUDENT1 ;