CREATE DATABASE NAMEES ;
USE NAMEES ;
CREATE TABLE AHMEDABAD
(
 PINCODE INT,
 CITYNAME VARCHAR(35),
 STATENAME VARCHAR(35)
) ;
SELECT *  FROM AHMEDABAD ;
INSERT INTO AHMEDABAD (PINCODE, CITYNAME, STATENAME) VALUES ( 380021 ,"AHMEDABAD","GUJARAT");
INSERT INTO AHMEDABAD (PINCODE, CITYNAME, STATENAME) VALUES ( 365975 ,"RAMJUK","MAHARASTRA");
INSERT INTO AHMEDABAD (PINCODE, CITYNAME, STATENAME) VALUES ( 669986 ,"RAJNAGAR","BANGLADESH");
USE NAMEES ;
SELECT * FROM AHMEDABAD ;
UPDATE AHMEDABAD SET CITYNAME = "KASHMIR" WHERE PINCODE = 365975 ;
DELETE FROM AHMEDABAD WHERE PINCODE = "869555" ;
CREATE TABLE AHMEDABAD1 SELECT * FROM AHMEDABAD ;
SELECT *  FROM AHMEDABAD1 ;
TRUNCATE TABLE AHMEDABAD1 ;
DROP TABLE AHMEDABAD1 ;