USE WEEK3 ;
SELECT * FROM RECORDES3;
SELECT DISTINCT  F_NAME FROM RECORDES3 ; 

CREATE TABLE ABCDE SELECT * FROM RECORDES3 ;

CREATE TABLE EXAMPLES1 
(  
N_ID INT PRIMARY KEY,
N_NAME VARCHAR(45),
N_BATCH VARCHAR(67)
);

INSERT INTO EXAMPLES1 (N_ID ,N_NAME)SELECT F_ID , F_CITY
FROM RECORDES3 ;

SELECT* FROM ABCDE ;
SELECT * FROM EXAMPLES1 ;
SELECT * FROM ABCDE LIMIT 4;

SELECT * FROM ABCDE WHERE F_NAME LIKE "H%" ;

SELECT * FROM ABCDE WHERE F_NAME LIKE "%Y" ;

SELECT * FROM ABCDE WHERE F_CITY LIKE "%HM%" ;

SELECT F_NAME, F_CITY FROM ABCDE WHERE V_NAME LIKE "M%H" ;


SELECT * FROM ABCDE WHERE V_CIT LIKE "H%H" ;

SELECT * FROM ABCDE WHERE V_NAME NOT LIKE "H%H" ;

SELECT * FROM EXCSV;

ALTER TABLE EXCSV 
DROP COLUMN SR  ;

ALTER TABLE EXCSV
ADD COLUMN SR INT PRIMARY KEY AUTO_INCREMENT ;


/* CHANGE TABLE USING ALTER TABLE AND ADD,REMOVE COLUMN,IMPORT DATA
*/