USE WEEK3 ;
SELECT * FROM EXCSV ;
CREATE TABLE DATEE 
(
 NNMAE VARCHAR(30),
 IID INT PRIMARY KEY,
 JOININGDATE DATE 
 );
 
 SELECT * FROM DATEE;
 ALTER TABLE DATEE 
 ADD COLUMN STATE VARCHAR (35) ;

SELECT * FROM DATEE 
WHERE  STATE IN ("GOA", "RAJASTHAN","GUJRAT");


SELECT * FROM DATEE 
WHERE IID IN (36,81,98);


SELECT * FROM DATEE 
WHERE GENDER NOT IN ("MALE");

ALTER TABLE DATEE
DROP COLUMN DATEECOL ;
 
 
SELECT * FROM DATEE 
WHERE IID BETWEEN 85 AND 115 ;


SELECT * FROM DATEE 
WHERE IID BETWEEN 100 AND 116 ;


SELECT * FROM DATEE 
WHERE JOININGDATE BETWEEN '2022-01-01' AND '2023-12-31'
AND SR NOT IN (1,5,7,9) ; 


SELECT * FROM DATEE 
WHERE JOININGDATE BETWEEN '2022-01-01' AND '2023-12-31'
AND GENDER NOT IN ("MALE") ; 
SELECT * FROM DATEE 
WHERE JOININGDATE BETWEEN '2022-09-01' AND '2023-12-31' ;

ALTER TABLE DATEE 
ADD COLUMN GENDER ENUM ("MALE","FEMALE") ;


