CREATE DATABASE WEEK4 ;
USE WEEK4 ;
CREATE TABLE ZOMATO 
(
 N_ID INT PRIMARY KEY ,
 N_NAME VARCHAR (30),
 N_CITY VARCHAR (30),
 N_AREA VARCHAR (30) 
 ) ;
 SELECT * FROM ZOMATO ;
 
 CREATE TABLE OLA 
 ( 
  F_NAME VARCHAR(25) PRIMARY KEY ,
  F_AREA VARCHAR(30) ,
  N_ID INT , 
  FOREIGN KEY (N_ID) REFERENCES ZOMATO (N_ID)
  ) ;
  
  SELECT * FROM ZOMATO 
  INNER JOIN OLA 
  ON ZOMATO.N_ID = OLA.N_ID ;
  
  
   SELECT * FROM ZOMATO 
  RIGHT JOIN OLA 
  ON ZOMATO.N_ID = OLA.N_ID ;
  
   SELECT * FROM ZOMATO 
  LEFT JOIN OLA 
  ON ZOMATO.N_ID = OLA.N_ID ;
  
