
USE WEEK4 ;
SELECT ZOMATO.N_ID , OLA.N_ID 
FROM ZOMATO 
CROSS JOIN OLA ;


SELECT ZOMATO.N_NAME , OLA.N_ID 
FROM ZOMATO 
CROSS JOIN OLA ;


SELECT COUNT(N_ID) , N_NAME
FROM ZOMATO
GROUP BY N_NAME ;



SELECT COUNT(N_NAME) , N_CITY
FROM ZOMATO
GROUP BY N_CITY;

SELECT COUNT(N_NAME) , N_CITY
FROM ZOMATO
GROUP BY N_CITY
HAVING COUNT(N_NAME) > 1 ;

/* SELECT PRODUCTNAME
FROM PRODUCTS
WHERE PRODUCTID = ANY
  (SELECT PRODUCTID
  FROM ORDERDETAILS
  WHERE QUANTITY = 10); */
  
SELECT N_NAME FROM ZOMATO
WHERE N_ID = ANY (SELECT  N_ID FROM OLA WHERE F_AREA = "JIKAR" );

SELECT N_ID FROM ZOMATO
WHERE N_ID = ANY (SELECT  N_ID FROM OLA WHERE N_ID = 3 );


SELECT COUNT(N_CITY) , N_NAME
FROM ZOMATO
GROUP BY N_NAME;




INSERT INTO TRIAL1 (ID, PINFO, ADD1, ADDAREA)
SELECT N_ID, N_NAME, N_CITY, N_AREA FROM ZOMATO ;  

SELECT ID ,SCORE ,
CASE 
     WHEN SCORE >35 THEN "CAN APPLY"
     WHEN SCORE > 25 THEN "RETRY ONLY WRONG ANS " 
     ELSE "START FROM FIRST"
END AS RESULT
FROM TRIAL1 ;