

USE WEEK5 ;
SELECT * FROM DATETIMES ;
COMMIT ;
UPDATE DATETIMES SET A_NAME = "LILA" WHERE A_ID = 23 ; 

ROLLBACK ;
UPDATE DATETIMES SET A_NAME = "KRISL" WHERE A_ID = 89 ;
ROLLBACK ; 



INSERT INTO DATETIMES VALUES ( 102 , "KILT" , 96657 , "F" , '2001-1-23'  );
SAVEPOINT NUM23 ;
DELETE FROM DATETIMES WHERE A_ID = 86 ;
SAVEPOINT RETURN86 ;


ROLLBACK  TO NUM ;
