CREATE DATABASE ASSESMENTSQL ;
USE ASSESMENTSQL ;
CREATE TABLE WORKER1
(
 WORKER_ID INT PRIMARY KEY AUTO_INCREMENT,
 FIRST_NAME VARCHAR(40),
 LAST_NAME VARCHAR(40),
 SALARY INT ,
 JOINING_DATE DATE ,
 DEPARTMENT VARCHAR(35) 
) ;
SELECT *  FROM WORKER1 ; 
INSERT INTO WORKER1 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (1,"MONIKA","ARORA",100000,2014/2/20,"HR");
INSERT INTO WORKER1 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (2,"NIHARIKA","VERMA",80000,2014/6/11,"ADMIN");
SELECT * FROM worker1 ORDER BY FIRST_NAME ASC ;
SELECT * FROM worker1 ORDER BY DEPARTMENT DESC ;
SELECT * FROM WORKER1 WHERE first_name = 'Vipul' OR first_name = 'Satish';
SELECT * FROM WORKER1 WHERE first_name LIKE '______h' ;
SELECT * FROM WORKER1 WHERE SALARY BETWEEN 100000 AND 200000 ;
SELECT  DISTINCT NOT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT FROM WORKER1 ;
SELECT * FROM WORKER1 LIMIT 6 ;





