CREATE DATABASE SQLPROJECT ;
USE SQLPROJECT ;
CREATE TABLE PASSANGERS 
(
 P_NAME VARCHAR(20),
 P_MO INT PRIMARY KEY,
 ARRIVING_LOC VARCHAR(30),
 ARRIVING_TIME TIME,
 DEPARTURE_LOC VARCHAR(30),
 DEPARTURE_TIME TIME ,
 PAYMENT ENUM('CASH','ONLINE')
 );
 
CREATE TABLE OLA 
(
 SR INT ,
 D_NAME VARCHAR(20),
 P_MO INT ,
 ARRIVING_LOC VARCHAR(30),
 ARRIVING_TIME TIME,
 OLA_CABID INT PRIMARY KEY ,
 OLA_NUMBERPLATE INT ,
 COST INT ,
 PAYMENT_RECE ENUM('CASH','ONLINE'),
 STATUSE VARCHAR(30),
 FOREIGN KEY (P_MO) REFERENCES PASSANGERS (P_MO)
 );
 
 
  
  
  
   SELECT * FROM PASSANGERS
  RIGHT JOIN OLA 
  ON PASSANGERS.P_MO = OLA.P_MO ;
  
   SELECT * FROM PASSANGERS 
  LEFT JOIN OLA 
  ON PASSANGERS.P_MO = OLA.P_MO ;
  
 SELECT * FROM PASSANGERS  
  INNER JOIN OLA 
  ON PASSANGERS.P_MO = OLA.P_MO ;
  
SELECT * FROM OLA 
CROSS JOIN PASSANGERS 
ON OLA.P_MO = PASSANGERS.P_MO ;


SELECT * FROM PASSANGERS 
CROSS JOIN OLA WHERE DATE1 BETWEEN  '2020-11-01' AND '2020-12-15' ; 


SELECT * FROM PASSANGERS 
INNER JOIN OLA WHERE DATE1 BETWEEN  '2020-11-01' AND '2020-12-15' ;


SELECT * FROM PASSANGERS 
FULL JOIN OLA WHERE DATE1 BETWEEN  '2020-11-01' AND '2020-12-15' ;

