CREATE DATABASE ASSIGNMENTSQL ;
USE ASSIGNMENTSQL ;
CREATE TABLE EMP
(
 SR INT PRIMARY KEY AUTO_INCREMENT,
 JOB_ID INT,
 EMP_FNAME VARCHAR(40),
 EMP_LNAME VARCHAR(40),
 HIRE_DATE DATE,
 DEP VARCHAR(30),
 SALARY INT
) ;
SELECT *  FROM EMP ;
SELECT * FROM EMP ;
ALTER TABLE EMP ADD COLUMN ENAME VARCHAR(30) ;
INSERT INTO EMP (SR, JOB_ID, EMP_FNAME, EMP_LNAME, HIRE_DATE, DEP, SALARY) VALUES ('1','11',"RAJESH","ROSHAN",'2020-01-01',"ADMIN",'2000');
INSERT INTO EMP VALUES ('2','22',"ROCKEY","MAKWANA",'2020-03-05',"SALES",'2500');
SELECT EMP_FNAME,DEP FROM EMP  ; 
SELECT HIRE_DATE,EMP_FNAME FROM EMP  ; 
SELECT CONCAT(EMP_Fname, ' ', EMP_Lname) AS 'EMPLOYEE' ,HIRE_DATE AS  'Title'FROM EMP;
SELECT HIRE_DATE,EMP_FNAME,DEP FROM EMP ;
SELECT * FROM EMP ;
SELECT EMP_FNAME,SALARY FROM EMP WHERE SALARY > '2000' ;
SELECT CONCAT(EMP_Fname, ' ', EMP_Lname) AS 'Name', HIRE_DATE AS 'Start Date' FROM EMP;
SELECT CONCAT(EMP_Fname, ' ', EMP_Lname) AS 'Name', SALARY FROM emp ORDER BY SALARY;
SELECT CONCAT(EMP_Fname, ' ', EMP_Lname) AS 'Name', DEP FROM emp ORDER BY SALARY DESC;



SELECT EMP_FNAME, DEP_NUM FROM EMP
WHERE COMISSION IS NOT NULL ;
  
   





SELECT MIN(SALARY) AS MINIMUM_SALARY FROM EMP ;
SELECT MAX(SALARY) AS MINIMUM_SALARY FROM EMP ;
SELECT AVG(SALARY) AS MINIMUM_SALARY FROM EMP ;

USE ASSIGNMENTSQL;

SELECT
    DEP_NUM,
    SUM(SALARY) AS TOTAL_SALAR_PAYOUT,
    SUM(COMISSION) AS TOTAL_COMMISSION_PAYOUT 
FROM
    EMP
WHERE COMISSION IS NOT NULL
GROUP BY
    DEP_NUM ;
    
    SELECT
    SUM(commission) AS total_commission_payout
FROM
    sales
WHERE
    commission IS NOT NULL;







