USE assesmentsql;

CREATE TABLE STUDENTS
(
STDID INT PRIMARY KEY,
STDNAME VARCHAR(35),
SEX VARCHAR(35),
PERCENTAGE INT,
CLASS INT,
SEC VARCHAR(35),
ASTREAM VARCHAR(35),
DOB DATE
);

SELECT *FROM STUDENTS ;
SELECT STDNAME, DOB  FROM STUDENTS ;
SELECT * FROM STUDENTS WHERE PERCENTAGE >= 80; 
SELECT * FROM STUDENTS WHERE percentage > 80; 
SELECT * FROM STUDENTS WHERE ASTREAM = 'SCIENCE' AND PERCENTAGE > 75;
