CREATE DATABASE ASSESMENTSQL ;
USE ASSESMENTSQL ;
CREATE TABLE WORKER1
(
 WORKER_ID INT PRIMARY KEY AUTO_INCREMENT,
 FIRST_NAME VARCHAR(40),
 LAST_NAME VARCHAR(40),
 SALARY INT ,
 JOINING_DATE DATE ,
 DEPARTMENT VARCHAR(35) 
) ;
SELECT *  FROM WORKER1 ;
INSERT INTO WORKER1 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (1,);
INSERT INTO WORKER1 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES ( 365975 ,"RAMJUK","MAHARASTRA");