CREATE TABLE STUDENT 
(
 STD_ID INT PRIMARY KEY AUTO_INCREMENT,
 STD_NAME VARCHAR(40),
 SEX VARCHAR(40),
 SALARY INT ,
 PERCENTAGE int ,
 CLASS INT,
 SEC VARCHAR(5),
 STREAM  VARCHAR(35),
 DOB DATE 
) ;

SELECT* FROM STUDENT ;