CREATE DATABASE ASSESMENTSQL ;
USE ASSESMENTSQL ;
CREATE TABLE WORKER1
(
 WORKER_ID INT PRIMARY KEY AUTO_INCREMENT,
 FIRST_NAME VARCHAR(40),
 LAST_NAME VARCHAR(40),
 SALARY INT ,
 JOINING_DATE DATETIME ,
 DEPARTMENT VARCHAR(35) 
) ;
SELECT *  FROM WORKER1 ;
INSERT INTO WORKER1 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (1,"MONIKA","ARORA",100000,"02-20-2014 09:00:00" ,"HR" );
INSERT INTO WORKER1 (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES ( 2 ,"NIHARIKA","VERMA",80000,"06-11-2014 09:00:00","ADMIN");
SELECT * FROM WORKER1 ;
SELECT *FROM WORKER1 WHERE FIRST_NAME IN ("VIPUL", "SATISH");

SELECT * FROM WORKER1 WHERE LENGTH(FIRST_NAME) = 6 AND  FIRST_NAME LIKE '%H';

SELECT * FROM WORKER1 WHERE SALARY < 100000;

SELECT DEPARTMENT, LAST_NAME, COUNT(*) AS count
FROM WORKER1
GROUP BY DEPARTMENT, LAST_NAME
HAVING COUNT > 1;

SELECT * FROM WORKER1 LIMIT 6;

SELECT DEPARTMENT, COUNT(*) AS TotalWorkers
FROM WORKER1
GROUP BY DEPARTMENT
HAVING COUNT(*) < 5;

SELECT Department, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS EmployeeName, Salary
FROM WORKER1
WHERE (Department, Salary) IN (
  SELECT Department, MAX(Salary)
  FROM WORKER1
  GROUP BY Department
);



